# Generated by Django 3.2 on 2021-10-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notez', '0003_auto_20211022_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Hello', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=248),
        ),
    ]
