# Generated by Django 3.2 on 2021-10-28 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notez', '0004_auto_20211023_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='colaborators',
        ),
        migrations.AddField(
            model_name='note',
            name='shares_with',
            field=models.ManyToManyField(blank=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
